### ISSUE TITLE
How to add CSV and Txt file?

### ISSUE THREAD

**Issue by Harmeet94Singh** [neilharvey/FileSignatures#52] opened 2023-03-30 06:31 UTC

**Comment by Harmeet94Singh** [comment] 2023-03-30 13:24
Does CSV of TXT file have any magic numbers?

**Comment by tiesont** [comment] 2023-03-30 19:03
This is a duplicate of a question asked in #51 - please close.

**Comment by neilharvey** [comment] 2023-03-30 19:07
@tiesont Thanks, I didn't spot it had been asked twice.

@Harmeet94Singh Just to confirm - no, a CSV file does not have any file signature that can be used to identify it.

**Closed as completed by neilharvey** 2023-03-30 19:07 UTC

**Comment by alikazai** [comment] 2024-11-25 19:13
Hi so this is really old thread but i came across it when trying to solve a similar problem. Since there is no real signature for csv's i decided to bypass the byte signature match for csv files.  

this is my custom Csv File format

``` csharp
/// <summary>
/// Specifies the format of a CSV file.
/// </summary>
public class CsvFileFormat : FileFormat
{
    public CsvFileFormat()
        : base([115], "text/csv", "csv")
    {
    }

    public override bool IsMatch(Stream stream)
    {
        if (stream == null || (stream.Length < HeaderLength && HeaderLength < int.MaxValue) || Offset > stream.Length)
            return false;

        stream.Position = Offset;

        return true;
    }
}
```

if anyone has a better approach please suggest it thanks.

Also im doing some content verification aswell but in my webapp before it gets upload to my api. 
basically that reads the content and looks for comma's

> WARNING
After messing with this and some other file types i noticed that this approach also assigns text/csv format to every fileformat verified which is not ideal. however the DetermineFileFormat function is returning the format with the largest headerlength matched which means it returns the correct formats for the others. 

downside to this is that if someone uploads eg an exe it will label it as text/csv which means you would probably need other layers of security like checking file type extension, in this case csv against the extension uploaded 

 

Need a better solution
